// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef UI_SCRSPLASHSCREEN_H
#define UI_SCRSPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSplashScreen
extern void ui_scrSplashScreen_screen_init(void);
extern void ui_scrSplashScreen_screen_destroy(void);
extern lv_obj_t * ui_scrSplashScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LoadingBar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrSplashScreen;
extern lv_obj_t * uic_LoadingBar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

