// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef UI_SCRTESTMACHINE_H
#define UI_SCRTESTMACHINE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTestMachine
extern void ui_scrTestMachine_screen_init(void);
extern void ui_scrTestMachine_screen_destroy(void);
extern lv_obj_t * ui_scrTestMachine;
extern lv_obj_t * ui_ProcessFlow1;
extern lv_obj_t * ui_ProcessFlowImage1;
extern lv_obj_t * ui_testSumpPump;
extern lv_obj_t * ui_testScrewPress;
extern lv_obj_t * ui_testTopGate;
extern lv_obj_t * ui_testBottomGate;
extern lv_obj_t * ui_testHeater;
extern lv_obj_t * ui_testMixer;
extern lv_obj_t * ui_testSettlingTankPump;
extern lv_obj_t * ui_testFilterTankPump;
extern lv_obj_t * ui_TestUpperLimitSettlingTank;
extern lv_obj_t * ui_TestLowerLimitSettlingTank;
extern lv_obj_t * ui_TestLowerLimitFilterTank;
extern lv_obj_t * ui_TestUpperLimitFilterTank;
extern lv_obj_t * ui_TestUpperLimitInputTank;
extern lv_obj_t * ui_TestLowerLimitInputTank;
extern lv_obj_t * ui_TestUpperLimitMixer;
extern void ui_event_btnStopTest(lv_event_t * e);
extern lv_obj_t * ui_btnStopTest;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrTestMachine;
extern lv_obj_t * uic_testSumpPump;
extern lv_obj_t * uic_testScrewPress;
extern lv_obj_t * uic_testTopGate;
extern lv_obj_t * uic_testBottomGate;
extern lv_obj_t * uic_testHeater;
extern lv_obj_t * uic_testMixer;
extern lv_obj_t * uic_testSettlingTankPump;
extern lv_obj_t * uic_testFilterTankPump;
extern lv_obj_t * uic_TestUpperLimitSettlingTank;
extern lv_obj_t * uic_TestLowerLimitSettlingTank;
extern lv_obj_t * uic_TestLowerLimitFilterTank;
extern lv_obj_t * uic_TestUpperLimitFilterTank;
extern lv_obj_t * uic_TestUpperLimitInputTank;
extern lv_obj_t * uic_TestLowerLimitInputTank;
extern lv_obj_t * uic_TestUpperLimitMixer;
extern lv_obj_t * uic_btnStopTest;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

