// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef UI_SCRMAINMENU_H
#define UI_SCRMAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMainMenu
extern void ui_scrMainMenu_screen_init(void);
extern void ui_scrMainMenu_screen_destroy(void);
extern lv_obj_t * ui_scrMainMenu;
extern void ui_event_btnRunAuto(lv_event_t * e);
extern lv_obj_t * ui_btnRunAuto;
extern lv_obj_t * ui_Label2;
extern void ui_event_btnTestMachine(lv_event_t * e);
extern lv_obj_t * ui_btnTestMachine;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnTestMachine1(lv_event_t * e);
extern lv_obj_t * ui_btnTestMachine1;
extern lv_obj_t * ui_btnSettings;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrMainMenu;
extern lv_obj_t * uic_btnRunAuto;
extern lv_obj_t * uic_btnTestMachine;
extern lv_obj_t * uic_btnSettings;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

