// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#include "../ui.h"

lv_obj_t * uic_btnSaveSetting;
lv_obj_t * uic_btnNextSetting;
lv_obj_t * uic_btnPreviousSetting;
lv_obj_t * uic_btnMultiplierFive;
lv_obj_t * uic_btnMultiplierOne;
lv_obj_t * uic_btnMultipliesPointOne;
lv_obj_t * uic_btnMinusSettings;
lv_obj_t * uic_btnPlusSettings;
lv_obj_t * uic_lblSettingValue;
lv_obj_t * uic_lblSettingTitle;
lv_obj_t * uic_srcSettings;
lv_obj_t * ui_scrSettings = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_lblSettingTitle = NULL;
lv_obj_t * ui_lblSettingValue = NULL;
lv_obj_t * ui_btnPlusSettings = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_btnMinusSettings = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_btnMultipliesPointOne = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_btnMultiplierOne = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_btnMultiplierFive = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_btnPreviousSetting = NULL;
lv_obj_t * ui_btnSettings2 = NULL;
lv_obj_t * ui_btnNextSetting = NULL;
lv_obj_t * ui_btnSettings1 = NULL;
lv_obj_t * ui_btnSaveSetting = NULL;
lv_obj_t * ui_btnSettings3 = NULL;
// event funtions
void ui_event_btnSaveSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMainMenu, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrMainMenu_screen_init);
    }
}

// build funtions

void ui_scrSettings_screen_init(void)
{
    ui_scrSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -200);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SETTINGS");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_scrSettings);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 800);
    lv_obj_set_height(ui_Container2, 300);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 4);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSettingTitle = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblSettingTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettingTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSettingTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSettingTitle, "SETTING TITLE");
    lv_obj_set_style_text_font(ui_lblSettingTitle, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSettingValue = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblSettingValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettingValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSettingValue, 0);
    lv_obj_set_y(ui_lblSettingValue, 80);
    lv_obj_set_align(ui_lblSettingValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblSettingValue, "1 Min");
    lv_obj_set_style_text_font(ui_lblSettingValue, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPlusSettings = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnPlusSettings, 100);
    lv_obj_set_height(ui_btnPlusSettings, 100);
    lv_obj_set_x(ui_btnPlusSettings, 300);
    lv_obj_set_y(ui_btnPlusSettings, 80);
    lv_obj_set_align(ui_btnPlusSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlusSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnPlusSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnPlusSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnPlusSettings, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPlusSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlusSettings, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPlusSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPlusSettings, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_btnPlusSettings);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "+");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMinusSettings = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnMinusSettings, 100);
    lv_obj_set_height(ui_btnMinusSettings, 100);
    lv_obj_set_x(ui_btnMinusSettings, -300);
    lv_obj_set_y(ui_btnMinusSettings, 80);
    lv_obj_set_align(ui_btnMinusSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMinusSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnMinusSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnMinusSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMinusSettings, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMinusSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnMinusSettings, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnMinusSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnMinusSettings, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_btnMinusSettings);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMultipliesPointOne = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnMultipliesPointOne, 100);
    lv_obj_set_height(ui_btnMultipliesPointOne, 100);
    lv_obj_set_x(ui_btnMultipliesPointOne, -120);
    lv_obj_set_y(ui_btnMultipliesPointOne, 80);
    lv_obj_set_align(ui_btnMultipliesPointOne, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMultipliesPointOne, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnMultipliesPointOne, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnMultipliesPointOne, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMultipliesPointOne, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMultipliesPointOne, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnMultipliesPointOne, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnMultipliesPointOne, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnMultipliesPointOne, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_btnMultipliesPointOne);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "0.1");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMultiplierOne = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnMultiplierOne, 100);
    lv_obj_set_height(ui_btnMultiplierOne, 100);
    lv_obj_set_x(ui_btnMultiplierOne, 0);
    lv_obj_set_y(ui_btnMultiplierOne, 80);
    lv_obj_set_align(ui_btnMultiplierOne, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMultiplierOne, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnMultiplierOne, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnMultiplierOne, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMultiplierOne, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMultiplierOne, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnMultiplierOne, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnMultiplierOne, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnMultiplierOne, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_btnMultiplierOne);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "1");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMultiplierFive = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnMultiplierFive, 100);
    lv_obj_set_height(ui_btnMultiplierFive, 100);
    lv_obj_set_x(ui_btnMultiplierFive, 120);
    lv_obj_set_y(ui_btnMultiplierFive, 80);
    lv_obj_set_align(ui_btnMultiplierFive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMultiplierFive, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnMultiplierFive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnMultiplierFive, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMultiplierFive, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMultiplierFive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnMultiplierFive, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnMultiplierFive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnMultiplierFive, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_btnMultiplierFive);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "5");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPreviousSetting = lv_button_create(ui_scrSettings);
    lv_obj_set_width(ui_btnPreviousSetting, 250);
    lv_obj_set_height(ui_btnPreviousSetting, 70);
    lv_obj_set_x(ui_btnPreviousSetting, -300);
    lv_obj_set_y(ui_btnPreviousSetting, 230);
    lv_obj_set_align(ui_btnPreviousSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPreviousSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnPreviousSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnPreviousSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnPreviousSetting, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPreviousSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPreviousSetting, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPreviousSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPreviousSetting, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettings2 = lv_label_create(ui_btnPreviousSetting);
    lv_obj_set_width(ui_btnSettings2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnSettings2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnSettings2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnSettings2, "PREVIOUS");
    lv_obj_set_style_text_font(ui_btnSettings2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnNextSetting = lv_button_create(ui_scrSettings);
    lv_obj_set_width(ui_btnNextSetting, 250);
    lv_obj_set_height(ui_btnNextSetting, 70);
    lv_obj_set_x(ui_btnNextSetting, 300);
    lv_obj_set_y(ui_btnNextSetting, 230);
    lv_obj_set_align(ui_btnNextSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnNextSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnNextSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnNextSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnNextSetting, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnNextSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnNextSetting, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnNextSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnNextSetting, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettings1 = lv_label_create(ui_btnNextSetting);
    lv_obj_set_width(ui_btnSettings1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnSettings1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnSettings1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnSettings1, "NEXT");
    lv_obj_set_style_text_font(ui_btnSettings1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveSetting = lv_button_create(ui_scrSettings);
    lv_obj_set_width(ui_btnSaveSetting, 250);
    lv_obj_set_height(ui_btnSaveSetting, 70);
    lv_obj_set_x(ui_btnSaveSetting, 0);
    lv_obj_set_y(ui_btnSaveSetting, 230);
    lv_obj_set_align(ui_btnSaveSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSaveSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSaveSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSaveSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSaveSetting, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSaveSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSaveSetting, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSaveSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSaveSetting, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettings3 = lv_label_create(ui_btnSaveSetting);
    lv_obj_set_width(ui_btnSettings3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnSettings3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnSettings3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnSettings3, "SAVE");
    lv_obj_set_style_text_font(ui_btnSettings3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnSaveSetting, ui_event_btnSaveSetting, LV_EVENT_ALL, NULL);
    uic_srcSettings = ui_scrSettings;
    uic_lblSettingTitle = ui_lblSettingTitle;
    uic_lblSettingValue = ui_lblSettingValue;
    uic_btnPlusSettings = ui_btnPlusSettings;
    uic_btnMinusSettings = ui_btnMinusSettings;
    uic_btnMultipliesPointOne = ui_btnMultipliesPointOne;
    uic_btnMultiplierOne = ui_btnMultiplierOne;
    uic_btnMultiplierFive = ui_btnMultiplierFive;
    uic_btnPreviousSetting = ui_btnPreviousSetting;
    uic_btnNextSetting = ui_btnNextSetting;
    uic_btnSaveSetting = ui_btnSaveSetting;

}

void ui_scrSettings_screen_destroy(void)
{
    if(ui_scrSettings) lv_obj_del(ui_scrSettings);

    // NULL screen variables
    uic_srcSettings = NULL;
    ui_scrSettings = NULL;
    ui_Label10 = NULL;
    ui_Container2 = NULL;
    uic_lblSettingTitle = NULL;
    ui_lblSettingTitle = NULL;
    uic_lblSettingValue = NULL;
    ui_lblSettingValue = NULL;
    uic_btnPlusSettings = NULL;
    ui_btnPlusSettings = NULL;
    ui_Label11 = NULL;
    uic_btnMinusSettings = NULL;
    ui_btnMinusSettings = NULL;
    ui_Label8 = NULL;
    uic_btnMultipliesPointOne = NULL;
    ui_btnMultipliesPointOne = NULL;
    ui_Label12 = NULL;
    uic_btnMultiplierOne = NULL;
    ui_btnMultiplierOne = NULL;
    ui_Label13 = NULL;
    uic_btnMultiplierFive = NULL;
    ui_btnMultiplierFive = NULL;
    ui_Label14 = NULL;
    uic_btnPreviousSetting = NULL;
    ui_btnPreviousSetting = NULL;
    ui_btnSettings2 = NULL;
    uic_btnNextSetting = NULL;
    ui_btnNextSetting = NULL;
    ui_btnSettings1 = NULL;
    uic_btnSaveSetting = NULL;
    ui_btnSaveSetting = NULL;
    ui_btnSettings3 = NULL;

}
