// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#include "../ui.h"

lv_obj_t * uic_LoadingBar;
lv_obj_t * uic_scrSplashScreen;
lv_obj_t * ui_scrSplashScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_LoadingBar = NULL;
// event funtions

// build funtions

void ui_scrSplashScreen_screen_init(void)
{
    ui_scrSplashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrSplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_scrSplashScreen, &ui_img_1396634952, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_scrSplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_scrSplashScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "FARM WASTE SOLID AND LIQUID SEPARATOR");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingBar = lv_bar_create(ui_scrSplashScreen);
    lv_bar_set_value(ui_LoadingBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LoadingBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LoadingBar, 488);
    lv_obj_set_height(ui_LoadingBar, 25);
    lv_obj_set_x(ui_LoadingBar, 0);
    lv_obj_set_y(ui_LoadingBar, 160);
    lv_obj_set_align(ui_LoadingBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LoadingBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LoadingBar,
                                                                                                 lv_obj_get_style_pad_right(ui_LoadingBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    uic_scrSplashScreen = ui_scrSplashScreen;
    uic_LoadingBar = ui_LoadingBar;

}

void ui_scrSplashScreen_screen_destroy(void)
{
    if(ui_scrSplashScreen) lv_obj_del(ui_scrSplashScreen);

    // NULL screen variables
    uic_scrSplashScreen = NULL;
    ui_scrSplashScreen = NULL;
    ui_Label1 = NULL;
    uic_LoadingBar = NULL;
    ui_LoadingBar = NULL;

}
