// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#include "../ui.h"

lv_obj_t * uic_btnSettings;
lv_obj_t * uic_btnTestMachine;
lv_obj_t * uic_btnRunAuto;
lv_obj_t * uic_scrMainMenu;
lv_obj_t * ui_scrMainMenu = NULL;
lv_obj_t * ui_btnRunAuto = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_btnTestMachine = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnTestMachine1 = NULL;
lv_obj_t * ui_btnSettings = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_btnRunAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrRunAuto, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrRunAuto_screen_init);
    }
}

void ui_event_btnTestMachine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTestMachine, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrTestMachine_screen_init);
    }
}

void ui_event_btnTestMachine1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrSettings, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrSettings_screen_init);
    }
}

// build funtions

void ui_scrMainMenu_screen_init(void)
{
    ui_scrMainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrMainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_scrMainMenu, &ui_img_1396634952, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_scrMainMenu, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRunAuto = lv_button_create(ui_scrMainMenu);
    lv_obj_set_width(ui_btnRunAuto, 250);
    lv_obj_set_height(ui_btnRunAuto, 70);
    lv_obj_set_x(ui_btnRunAuto, -320);
    lv_obj_set_y(ui_btnRunAuto, 100);
    lv_obj_set_align(ui_btnRunAuto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRunAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnRunAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnRunAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRunAuto, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRunAuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRunAuto, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRunAuto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRunAuto, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_btnRunAuto);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "RUN AUTO");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTestMachine = lv_button_create(ui_scrMainMenu);
    lv_obj_set_width(ui_btnTestMachine, 250);
    lv_obj_set_height(ui_btnTestMachine, 70);
    lv_obj_set_x(ui_btnTestMachine, 0);
    lv_obj_set_y(ui_btnTestMachine, 100);
    lv_obj_set_align(ui_btnTestMachine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTestMachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTestMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTestMachine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTestMachine, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTestMachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTestMachine, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnTestMachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTestMachine, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btnTestMachine);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TEST MACHINE");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTestMachine1 = lv_button_create(ui_scrMainMenu);
    lv_obj_set_width(ui_btnTestMachine1, 250);
    lv_obj_set_height(ui_btnTestMachine1, 70);
    lv_obj_set_x(ui_btnTestMachine1, 320);
    lv_obj_set_y(ui_btnTestMachine1, 100);
    lv_obj_set_align(ui_btnTestMachine1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTestMachine1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTestMachine1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTestMachine1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTestMachine1, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTestMachine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTestMachine1, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnTestMachine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTestMachine1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSettings = lv_label_create(ui_btnTestMachine1);
    lv_obj_set_width(ui_btnSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnSettings, "SETTINGS");
    lv_obj_set_style_text_font(ui_btnSettings, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_scrMainMenu);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -200);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "MAIN MENU");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnRunAuto, ui_event_btnRunAuto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTestMachine, ui_event_btnTestMachine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTestMachine1, ui_event_btnTestMachine1, LV_EVENT_ALL, NULL);
    uic_scrMainMenu = ui_scrMainMenu;
    uic_btnRunAuto = ui_btnRunAuto;
    uic_btnTestMachine = ui_btnTestMachine;
    uic_btnSettings = ui_btnSettings;

}

void ui_scrMainMenu_screen_destroy(void)
{
    if(ui_scrMainMenu) lv_obj_del(ui_scrMainMenu);

    // NULL screen variables
    uic_scrMainMenu = NULL;
    ui_scrMainMenu = NULL;
    uic_btnRunAuto = NULL;
    ui_btnRunAuto = NULL;
    ui_Label2 = NULL;
    uic_btnTestMachine = NULL;
    ui_btnTestMachine = NULL;
    ui_Label3 = NULL;
    ui_btnTestMachine1 = NULL;
    uic_btnSettings = NULL;
    ui_btnSettings = NULL;
    ui_Label4 = NULL;

}
