// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef UI_SCRSETTINGS_H
#define UI_SCRSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSettings
extern void ui_scrSettings_screen_init(void);
extern void ui_scrSettings_screen_destroy(void);
extern lv_obj_t * ui_scrSettings;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_lblSettingTitle;
extern lv_obj_t * ui_lblSettingValue;
extern lv_obj_t * ui_btnPlusSettings;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_btnMinusSettings;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_btnMultipliesPointOne;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_btnMultiplierOne;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_btnMultiplierFive;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_btnPreviousSetting;
extern lv_obj_t * ui_btnSettings2;
extern lv_obj_t * ui_btnNextSetting;
extern lv_obj_t * ui_btnSettings1;
extern void ui_event_btnSaveSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSaveSetting;
extern lv_obj_t * ui_btnSettings3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_srcSettings;
extern lv_obj_t * uic_lblSettingTitle;
extern lv_obj_t * uic_lblSettingValue;
extern lv_obj_t * uic_btnPlusSettings;
extern lv_obj_t * uic_btnMinusSettings;
extern lv_obj_t * uic_btnMultipliesPointOne;
extern lv_obj_t * uic_btnMultiplierOne;
extern lv_obj_t * uic_btnMultiplierFive;
extern lv_obj_t * uic_btnPreviousSetting;
extern lv_obj_t * uic_btnNextSetting;
extern lv_obj_t * uic_btnSaveSetting;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

