// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#include "../ui.h"
#include "app_machine.h"
#include "app_process.h"

lv_obj_t * uic_btnEmergencyStop;
lv_obj_t * uic_UpperLimitMixer;
lv_obj_t * uic_LowerLimitInputTank;
lv_obj_t * uic_UpperLimitInputTank;
lv_obj_t * uic_UpperLimitFilterTank;
lv_obj_t * uic_LowerLimitFilterTank;
lv_obj_t * uic_LowerLimitSettlingTank;
lv_obj_t * uic_UpperLimitSettlingTank;
lv_obj_t * uic_FilterTankPump;
lv_obj_t * uic_SettlingTankPump;
lv_obj_t * uic_Mixer;
lv_obj_t * uic_Heater;
lv_obj_t * uic_BottomGate;
lv_obj_t * uic_TopGate;
lv_obj_t * uic_ScrewPress;
lv_obj_t * uic_SumpPump;
lv_obj_t * uic_lblCurrentStatus;
lv_obj_t * uic_cntnrStatus;
lv_obj_t * uic_ProcessFlowImage;
lv_obj_t * uic_ProcessFlowControl;
lv_obj_t * ui_scrRunAuto = NULL;
lv_obj_t * ui_ProcessFlow = NULL;
lv_obj_t * ui_ProcessFlowImage = NULL;
lv_obj_t * ui_cntnrStatus1 = NULL;
lv_obj_t * ui_lblCurrentStatus1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_cntnrStatus = NULL;
lv_obj_t * ui_lblCurrentStatus = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_SumpPump = NULL;
lv_obj_t * ui_ScrewPress = NULL;
lv_obj_t * ui_TopGate = NULL;
lv_obj_t * ui_BottomGate = NULL;
lv_obj_t * ui_Heater = NULL;
lv_obj_t * ui_Mixer = NULL;
lv_obj_t * ui_SettlingTankPump = NULL;
lv_obj_t * ui_FilterTankPump = NULL;
lv_obj_t * ui_UpperLimitSettlingTank = NULL;
lv_obj_t * ui_LowerLimitSettlingTank = NULL;
lv_obj_t * ui_LowerLimitFilterTank = NULL;
lv_obj_t * ui_UpperLimitFilterTank = NULL;
lv_obj_t * ui_UpperLimitInputTank = NULL;
lv_obj_t * ui_LowerLimitInputTank = NULL;
lv_obj_t * ui_UpperLimitMixer = NULL;
lv_obj_t * ui_btnEmergencyStop = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_btnEmergencyStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        /* 1. Stop the auto process task */
        app_process_stop();
        /* 2. De-energise all relays immediately (gates spring to safe/closed position) */
        app_machine_all_relays_off();
        /* 3. Return to Main Menu */
        _ui_screen_change(&ui_scrMainMenu, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrMainMenu_screen_init);
    }
}

// build funtions

void ui_scrRunAuto_screen_init(void)
{
    ui_scrRunAuto = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrRunAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProcessFlow = lv_obj_create(ui_scrRunAuto);
    lv_obj_remove_style_all(ui_ProcessFlow);
    lv_obj_set_width(ui_ProcessFlow, 875);
    lv_obj_set_height(ui_ProcessFlow, 500);
    lv_obj_set_x(ui_ProcessFlow, 0);
    lv_obj_set_y(ui_ProcessFlow, 30);
    lv_obj_set_align(ui_ProcessFlow, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ProcessFlow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_ProcessFlow, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProcessFlowImage = lv_image_create(ui_ProcessFlow);
    lv_image_set_src(ui_ProcessFlowImage, &ui_img_process_flow_water_sepparator_png);
    lv_obj_set_width(ui_ProcessFlowImage, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ProcessFlowImage, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_ProcessFlowImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProcessFlowImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ProcessFlowImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ProcessFlowImage, 255);

    ui_cntnrStatus1 = lv_obj_create(ui_ProcessFlow);
    lv_obj_remove_style_all(ui_cntnrStatus1);
    lv_obj_set_width(ui_cntnrStatus1, 320);
    lv_obj_set_height(ui_cntnrStatus1, 30);
    lv_obj_set_x(ui_cntnrStatus1, 0);
    lv_obj_set_y(ui_cntnrStatus1, 40);
    lv_obj_remove_flag(ui_cntnrStatus1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCurrentStatus1 = lv_label_create(ui_cntnrStatus1);
    lv_obj_set_width(ui_lblCurrentStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCurrentStatus1, 70);
    lv_obj_set_y(ui_lblCurrentStatus1, 0);
    lv_label_set_text(ui_lblCurrentStatus1, "00:00:00");
    lv_obj_set_style_text_align(ui_lblCurrentStatus1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCurrentStatus1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_cntnrStatus1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label7, "TIME:");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cntnrStatus = lv_obj_create(ui_ProcessFlow);
    lv_obj_remove_style_all(ui_cntnrStatus);
    lv_obj_set_width(ui_cntnrStatus, 320);
    lv_obj_set_height(ui_cntnrStatus, 30);
    lv_obj_remove_flag(ui_cntnrStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCurrentStatus = lv_label_create(ui_cntnrStatus);
    lv_obj_set_width(ui_lblCurrentStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCurrentStatus, 101);
    lv_obj_set_y(ui_lblCurrentStatus, 0);
    lv_label_set_text(ui_lblCurrentStatus, "CURRENT STATUS");
    lv_obj_set_style_text_align(ui_lblCurrentStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblCurrentStatus, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_cntnrStatus);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label6, "STATUS: ");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SumpPump = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_SumpPump, 50);
    lv_obj_set_height(ui_SumpPump, 50);
    lv_obj_set_x(ui_SumpPump, 384);
    lv_obj_set_y(ui_SumpPump, 63);
    lv_obj_set_align(ui_SumpPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SumpPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SumpPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SumpPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrewPress = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_ScrewPress, 50);
    lv_obj_set_height(ui_ScrewPress, 50);
    lv_obj_set_x(ui_ScrewPress, -151);
    lv_obj_set_y(ui_ScrewPress, -96);
    lv_obj_set_align(ui_ScrewPress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrewPress, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrewPress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrewPress, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopGate = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_TopGate, 50);
    lv_obj_set_height(ui_TopGate, 50);
    lv_obj_set_x(ui_TopGate, -254);
    lv_obj_set_y(ui_TopGate, -39);
    lv_obj_set_align(ui_TopGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TopGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopGate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomGate = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_BottomGate, 50);
    lv_obj_set_height(ui_BottomGate, 50);
    lv_obj_set_x(ui_BottomGate, -395);
    lv_obj_set_y(ui_BottomGate, 128);
    lv_obj_set_align(ui_BottomGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BottomGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomGate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Heater = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_Heater, 50);
    lv_obj_set_height(ui_Heater, 50);
    lv_obj_set_x(ui_Heater, -273);
    lv_obj_set_y(ui_Heater, 167);
    lv_obj_set_align(ui_Heater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Heater, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Heater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Heater, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mixer = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_Mixer, 50);
    lv_obj_set_height(ui_Mixer, 50);
    lv_obj_set_x(ui_Mixer, -169);
    lv_obj_set_y(ui_Mixer, 86);
    lv_obj_set_align(ui_Mixer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mixer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Mixer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Mixer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettlingTankPump = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_SettlingTankPump, 50);
    lv_obj_set_height(ui_SettlingTankPump, 50);
    lv_obj_set_x(ui_SettlingTankPump, -29);
    lv_obj_set_y(ui_SettlingTankPump, 213);
    lv_obj_set_align(ui_SettlingTankPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettlingTankPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettlingTankPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettlingTankPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FilterTankPump = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_FilterTankPump, 50);
    lv_obj_set_height(ui_FilterTankPump, 50);
    lv_obj_set_x(ui_FilterTankPump, 105);
    lv_obj_set_y(ui_FilterTankPump, 213);
    lv_obj_set_align(ui_FilterTankPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FilterTankPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_FilterTankPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FilterTankPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpperLimitSettlingTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_UpperLimitSettlingTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpperLimitSettlingTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpperLimitSettlingTank, -70);
    lv_obj_set_y(ui_UpperLimitSettlingTank, 41);
    lv_obj_set_align(ui_UpperLimitSettlingTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpperLimitSettlingTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_UpperLimitSettlingTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LowerLimitSettlingTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_LowerLimitSettlingTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowerLimitSettlingTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowerLimitSettlingTank, -71);
    lv_obj_set_y(ui_LowerLimitSettlingTank, 151);
    lv_obj_set_align(ui_LowerLimitSettlingTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowerLimitSettlingTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LowerLimitSettlingTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LowerLimitFilterTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_LowerLimitFilterTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowerLimitFilterTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowerLimitFilterTank, 75);
    lv_obj_set_y(ui_LowerLimitFilterTank, 154);
    lv_obj_set_align(ui_LowerLimitFilterTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowerLimitFilterTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LowerLimitFilterTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_UpperLimitFilterTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_UpperLimitFilterTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpperLimitFilterTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpperLimitFilterTank, 76);
    lv_obj_set_y(ui_UpperLimitFilterTank, 37);
    lv_obj_set_align(ui_UpperLimitFilterTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpperLimitFilterTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_UpperLimitFilterTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_UpperLimitInputTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_UpperLimitInputTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpperLimitInputTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpperLimitInputTank, -50);
    lv_obj_set_y(ui_UpperLimitInputTank, -189);
    lv_obj_set_align(ui_UpperLimitInputTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpperLimitInputTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_UpperLimitInputTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LowerLimitInputTank = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_LowerLimitInputTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowerLimitInputTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowerLimitInputTank, -49);
    lv_obj_set_y(ui_LowerLimitInputTank, -112);
    lv_obj_set_align(ui_LowerLimitInputTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowerLimitInputTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LowerLimitInputTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_UpperLimitMixer = lv_checkbox_create(ui_ProcessFlow);
    lv_obj_set_width(ui_UpperLimitMixer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpperLimitMixer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpperLimitMixer, -374);
    lv_obj_set_y(ui_UpperLimitMixer, 29);
    lv_obj_set_align(ui_UpperLimitMixer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpperLimitMixer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_UpperLimitMixer, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_btnEmergencyStop = lv_button_create(ui_ProcessFlow);
    lv_obj_set_width(ui_btnEmergencyStop, 180);
    lv_obj_set_height(ui_btnEmergencyStop, 60);
    lv_obj_set_x(ui_btnEmergencyStop, 0);
    lv_obj_set_y(ui_btnEmergencyStop, 100);
    lv_obj_add_flag(ui_btnEmergencyStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnEmergencyStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnEmergencyStop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnEmergencyStop, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnEmergencyStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnEmergencyStop, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnEmergencyStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnEmergencyStop, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_btnEmergencyStop);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "STOP");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_scrRunAuto);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -250);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "RUN AUTO");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnEmergencyStop, ui_event_btnEmergencyStop, LV_EVENT_ALL, NULL);
    uic_ProcessFlowControl = ui_scrRunAuto;
    uic_ProcessFlowImage = ui_ProcessFlowImage;
    uic_cntnrStatus = ui_cntnrStatus;
    uic_lblCurrentStatus = ui_lblCurrentStatus;
    uic_SumpPump = ui_SumpPump;
    uic_ScrewPress = ui_ScrewPress;
    uic_TopGate = ui_TopGate;
    uic_BottomGate = ui_BottomGate;
    uic_Heater = ui_Heater;
    uic_Mixer = ui_Mixer;
    uic_SettlingTankPump = ui_SettlingTankPump;
    uic_FilterTankPump = ui_FilterTankPump;
    uic_UpperLimitSettlingTank = ui_UpperLimitSettlingTank;
    uic_LowerLimitSettlingTank = ui_LowerLimitSettlingTank;
    uic_LowerLimitFilterTank = ui_LowerLimitFilterTank;
    uic_UpperLimitFilterTank = ui_UpperLimitFilterTank;
    uic_UpperLimitInputTank = ui_UpperLimitInputTank;
    uic_LowerLimitInputTank = ui_LowerLimitInputTank;
    uic_UpperLimitMixer = ui_UpperLimitMixer;
    uic_btnEmergencyStop = ui_btnEmergencyStop;

}

void ui_scrRunAuto_screen_destroy(void)
{
    if(ui_scrRunAuto) lv_obj_del(ui_scrRunAuto);

    // NULL screen variables
    uic_ProcessFlowControl = NULL;
    ui_scrRunAuto = NULL;
    ui_ProcessFlow = NULL;
    uic_ProcessFlowImage = NULL;
    ui_ProcessFlowImage = NULL;
    ui_cntnrStatus1 = NULL;
    ui_lblCurrentStatus1 = NULL;
    ui_Label7 = NULL;
    uic_cntnrStatus = NULL;
    ui_cntnrStatus = NULL;
    uic_lblCurrentStatus = NULL;
    ui_lblCurrentStatus = NULL;
    ui_Label6 = NULL;
    uic_SumpPump = NULL;
    ui_SumpPump = NULL;
    uic_ScrewPress = NULL;
    ui_ScrewPress = NULL;
    uic_TopGate = NULL;
    ui_TopGate = NULL;
    uic_BottomGate = NULL;
    ui_BottomGate = NULL;
    uic_Heater = NULL;
    ui_Heater = NULL;
    uic_Mixer = NULL;
    ui_Mixer = NULL;
    uic_SettlingTankPump = NULL;
    ui_SettlingTankPump = NULL;
    uic_FilterTankPump = NULL;
    ui_FilterTankPump = NULL;
    uic_UpperLimitSettlingTank = NULL;
    ui_UpperLimitSettlingTank = NULL;
    uic_LowerLimitSettlingTank = NULL;
    ui_LowerLimitSettlingTank = NULL;
    uic_LowerLimitFilterTank = NULL;
    ui_LowerLimitFilterTank = NULL;
    uic_UpperLimitFilterTank = NULL;
    ui_UpperLimitFilterTank = NULL;
    uic_UpperLimitInputTank = NULL;
    ui_UpperLimitInputTank = NULL;
    uic_LowerLimitInputTank = NULL;
    ui_LowerLimitInputTank = NULL;
    uic_UpperLimitMixer = NULL;
    ui_UpperLimitMixer = NULL;
    uic_btnEmergencyStop = NULL;
    ui_btnEmergencyStop = NULL;
    ui_Label9 = NULL;
    ui_Label5 = NULL;

}
