// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef UI_SCRRUNAUTO_H
#define UI_SCRRUNAUTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrRunAuto
extern void ui_scrRunAuto_screen_init(void);
extern void ui_scrRunAuto_screen_destroy(void);
extern lv_obj_t * ui_scrRunAuto;
extern lv_obj_t * ui_ProcessFlow;
extern lv_obj_t * ui_ProcessFlowImage;
extern lv_obj_t * ui_cntnrStatus1;
extern lv_obj_t * ui_lblCurrentStatus1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_cntnrStatus;
extern lv_obj_t * ui_lblCurrentStatus;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SumpPump;
extern lv_obj_t * ui_ScrewPress;
extern lv_obj_t * ui_TopGate;
extern lv_obj_t * ui_BottomGate;
extern lv_obj_t * ui_Heater;
extern lv_obj_t * ui_Mixer;
extern lv_obj_t * ui_SettlingTankPump;
extern lv_obj_t * ui_FilterTankPump;
extern lv_obj_t * ui_UpperLimitSettlingTank;
extern lv_obj_t * ui_LowerLimitSettlingTank;
extern lv_obj_t * ui_LowerLimitFilterTank;
extern lv_obj_t * ui_UpperLimitFilterTank;
extern lv_obj_t * ui_UpperLimitInputTank;
extern lv_obj_t * ui_LowerLimitInputTank;
extern lv_obj_t * ui_UpperLimitMixer;
extern void ui_event_btnEmergencyStop(lv_event_t * e);
extern lv_obj_t * ui_btnEmergencyStop;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ProcessFlowControl;
extern lv_obj_t * uic_ProcessFlowImage;
extern lv_obj_t * uic_cntnrStatus;
extern lv_obj_t * uic_lblCurrentStatus;
extern lv_obj_t * uic_SumpPump;
extern lv_obj_t * uic_ScrewPress;
extern lv_obj_t * uic_TopGate;
extern lv_obj_t * uic_BottomGate;
extern lv_obj_t * uic_Heater;
extern lv_obj_t * uic_Mixer;
extern lv_obj_t * uic_SettlingTankPump;
extern lv_obj_t * uic_FilterTankPump;
extern lv_obj_t * uic_UpperLimitSettlingTank;
extern lv_obj_t * uic_LowerLimitSettlingTank;
extern lv_obj_t * uic_LowerLimitFilterTank;
extern lv_obj_t * uic_UpperLimitFilterTank;
extern lv_obj_t * uic_UpperLimitInputTank;
extern lv_obj_t * uic_LowerLimitInputTank;
extern lv_obj_t * uic_UpperLimitMixer;
extern lv_obj_t * uic_btnEmergencyStop;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

