// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#include "../ui.h"

lv_obj_t * uic_btnStopTest;
lv_obj_t * uic_TestUpperLimitMixer;
lv_obj_t * uic_TestLowerLimitInputTank;
lv_obj_t * uic_TestUpperLimitInputTank;
lv_obj_t * uic_TestUpperLimitFilterTank;
lv_obj_t * uic_TestLowerLimitFilterTank;
lv_obj_t * uic_TestLowerLimitSettlingTank;
lv_obj_t * uic_TestUpperLimitSettlingTank;
lv_obj_t * uic_testFilterTankPump;
lv_obj_t * uic_testSettlingTankPump;
lv_obj_t * uic_testMixer;
lv_obj_t * uic_testHeater;
lv_obj_t * uic_testBottomGate;
lv_obj_t * uic_testTopGate;
lv_obj_t * uic_testScrewPress;
lv_obj_t * uic_testSumpPump;
lv_obj_t * uic_scrTestMachine;
lv_obj_t * ui_scrTestMachine = NULL;
lv_obj_t * ui_ProcessFlow1 = NULL;
lv_obj_t * ui_ProcessFlowImage1 = NULL;
lv_obj_t * ui_testSumpPump = NULL;
lv_obj_t * ui_testScrewPress = NULL;
lv_obj_t * ui_testTopGate = NULL;
lv_obj_t * ui_testBottomGate = NULL;
lv_obj_t * ui_testHeater = NULL;
lv_obj_t * ui_testMixer = NULL;
lv_obj_t * ui_testSettlingTankPump = NULL;
lv_obj_t * ui_testFilterTankPump = NULL;
lv_obj_t * ui_TestUpperLimitSettlingTank = NULL;
lv_obj_t * ui_TestLowerLimitSettlingTank = NULL;
lv_obj_t * ui_TestLowerLimitFilterTank = NULL;
lv_obj_t * ui_TestUpperLimitFilterTank = NULL;
lv_obj_t * ui_TestUpperLimitInputTank = NULL;
lv_obj_t * ui_TestLowerLimitInputTank = NULL;
lv_obj_t * ui_TestUpperLimitMixer = NULL;
lv_obj_t * ui_btnStopTest = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
// event funtions
void ui_event_btnStopTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMainMenu, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_scrMainMenu_screen_init);
    }
}

// build funtions

void ui_scrTestMachine_screen_init(void)
{
    ui_scrTestMachine = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrTestMachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProcessFlow1 = lv_obj_create(ui_scrTestMachine);
    lv_obj_remove_style_all(ui_ProcessFlow1);
    lv_obj_set_width(ui_ProcessFlow1, 875);
    lv_obj_set_height(ui_ProcessFlow1, 500);
    lv_obj_set_x(ui_ProcessFlow1, 0);
    lv_obj_set_y(ui_ProcessFlow1, 30);
    lv_obj_set_align(ui_ProcessFlow1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ProcessFlow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_ProcessFlow1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProcessFlowImage1 = lv_image_create(ui_ProcessFlow1);
    lv_image_set_src(ui_ProcessFlowImage1, &ui_img_1839083635);
    lv_obj_set_width(ui_ProcessFlowImage1, lv_pct(100));
    lv_obj_set_height(ui_ProcessFlowImage1, lv_pct(100));
    lv_obj_set_align(ui_ProcessFlowImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProcessFlowImage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ProcessFlowImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ProcessFlowImage1, 75);

    ui_testSumpPump = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testSumpPump, 50);
    lv_obj_set_height(ui_testSumpPump, 50);
    lv_obj_set_x(ui_testSumpPump, 384);
    lv_obj_set_y(ui_testSumpPump, 63);
    lv_obj_set_align(ui_testSumpPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testSumpPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testSumpPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testSumpPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testScrewPress = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testScrewPress, 50);
    lv_obj_set_height(ui_testScrewPress, 50);
    lv_obj_set_x(ui_testScrewPress, -151);
    lv_obj_set_y(ui_testScrewPress, -96);
    lv_obj_set_align(ui_testScrewPress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testScrewPress, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testScrewPress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testScrewPress, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testTopGate = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testTopGate, 50);
    lv_obj_set_height(ui_testTopGate, 50);
    lv_obj_set_x(ui_testTopGate, -254);
    lv_obj_set_y(ui_testTopGate, -39);
    lv_obj_set_align(ui_testTopGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testTopGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testTopGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testTopGate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testBottomGate = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testBottomGate, 50);
    lv_obj_set_height(ui_testBottomGate, 50);
    lv_obj_set_x(ui_testBottomGate, -395);
    lv_obj_set_y(ui_testBottomGate, 128);
    lv_obj_set_align(ui_testBottomGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testBottomGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testBottomGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testBottomGate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testHeater = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testHeater, 50);
    lv_obj_set_height(ui_testHeater, 50);
    lv_obj_set_x(ui_testHeater, -273);
    lv_obj_set_y(ui_testHeater, 167);
    lv_obj_set_align(ui_testHeater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testHeater, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testHeater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testHeater, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testMixer = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testMixer, 50);
    lv_obj_set_height(ui_testMixer, 50);
    lv_obj_set_x(ui_testMixer, -169);
    lv_obj_set_y(ui_testMixer, 86);
    lv_obj_set_align(ui_testMixer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testMixer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testMixer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testMixer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testSettlingTankPump = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testSettlingTankPump, 50);
    lv_obj_set_height(ui_testSettlingTankPump, 50);
    lv_obj_set_x(ui_testSettlingTankPump, -29);
    lv_obj_set_y(ui_testSettlingTankPump, 213);
    lv_obj_set_align(ui_testSettlingTankPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testSettlingTankPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testSettlingTankPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testSettlingTankPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testFilterTankPump = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_testFilterTankPump, 50);
    lv_obj_set_height(ui_testFilterTankPump, 50);
    lv_obj_set_x(ui_testFilterTankPump, 105);
    lv_obj_set_y(ui_testFilterTankPump, 213);
    lv_obj_set_align(ui_testFilterTankPump, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_testFilterTankPump, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_testFilterTankPump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_testFilterTankPump, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestUpperLimitSettlingTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestUpperLimitSettlingTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestUpperLimitSettlingTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestUpperLimitSettlingTank, -70);
    lv_obj_set_y(ui_TestUpperLimitSettlingTank, 41);
    lv_obj_set_align(ui_TestUpperLimitSettlingTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestUpperLimitSettlingTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestUpperLimitSettlingTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestLowerLimitSettlingTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestLowerLimitSettlingTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestLowerLimitSettlingTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestLowerLimitSettlingTank, -71);
    lv_obj_set_y(ui_TestLowerLimitSettlingTank, 151);
    lv_obj_set_align(ui_TestLowerLimitSettlingTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestLowerLimitSettlingTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestLowerLimitSettlingTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestLowerLimitFilterTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestLowerLimitFilterTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestLowerLimitFilterTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestLowerLimitFilterTank, 75);
    lv_obj_set_y(ui_TestLowerLimitFilterTank, 154);
    lv_obj_set_align(ui_TestLowerLimitFilterTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestLowerLimitFilterTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestLowerLimitFilterTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestUpperLimitFilterTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestUpperLimitFilterTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestUpperLimitFilterTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestUpperLimitFilterTank, 76);
    lv_obj_set_y(ui_TestUpperLimitFilterTank, 37);
    lv_obj_set_align(ui_TestUpperLimitFilterTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestUpperLimitFilterTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestUpperLimitFilterTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestUpperLimitInputTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestUpperLimitInputTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestUpperLimitInputTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestUpperLimitInputTank, -50);
    lv_obj_set_y(ui_TestUpperLimitInputTank, -189);
    lv_obj_set_align(ui_TestUpperLimitInputTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestUpperLimitInputTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestUpperLimitInputTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestLowerLimitInputTank = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestLowerLimitInputTank, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestLowerLimitInputTank, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestLowerLimitInputTank, -49);
    lv_obj_set_y(ui_TestLowerLimitInputTank, -112);
    lv_obj_set_align(ui_TestLowerLimitInputTank, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestLowerLimitInputTank, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestLowerLimitInputTank, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TestUpperLimitMixer = lv_checkbox_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_TestUpperLimitMixer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestUpperLimitMixer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestUpperLimitMixer, -374);
    lv_obj_set_y(ui_TestUpperLimitMixer, 29);
    lv_obj_set_align(ui_TestUpperLimitMixer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestUpperLimitMixer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TestUpperLimitMixer, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_btnStopTest = lv_button_create(ui_ProcessFlow1);
    lv_obj_set_width(ui_btnStopTest, 180);
    lv_obj_set_height(ui_btnStopTest, 60);
    lv_obj_set_x(ui_btnStopTest, 0);
    lv_obj_set_y(ui_btnStopTest, 30);
    lv_obj_add_flag(ui_btnStopTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnStopTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnStopTest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnStopTest, lv_color_hex(0xCB3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStopTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnStopTest, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnStopTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnStopTest, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_btnStopTest);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "STOP TEST");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_scrTestMachine);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -250);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "TEST MACHINE");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnStopTest, ui_event_btnStopTest, LV_EVENT_ALL, NULL);
    uic_scrTestMachine = ui_scrTestMachine;
    uic_testSumpPump = ui_testSumpPump;
    uic_testScrewPress = ui_testScrewPress;
    uic_testTopGate = ui_testTopGate;
    uic_testBottomGate = ui_testBottomGate;
    uic_testHeater = ui_testHeater;
    uic_testMixer = ui_testMixer;
    uic_testSettlingTankPump = ui_testSettlingTankPump;
    uic_testFilterTankPump = ui_testFilterTankPump;
    uic_TestUpperLimitSettlingTank = ui_TestUpperLimitSettlingTank;
    uic_TestLowerLimitSettlingTank = ui_TestLowerLimitSettlingTank;
    uic_TestLowerLimitFilterTank = ui_TestLowerLimitFilterTank;
    uic_TestUpperLimitFilterTank = ui_TestUpperLimitFilterTank;
    uic_TestUpperLimitInputTank = ui_TestUpperLimitInputTank;
    uic_TestLowerLimitInputTank = ui_TestLowerLimitInputTank;
    uic_TestUpperLimitMixer = ui_TestUpperLimitMixer;
    uic_btnStopTest = ui_btnStopTest;

}

void ui_scrTestMachine_screen_destroy(void)
{
    if(ui_scrTestMachine) lv_obj_del(ui_scrTestMachine);

    // NULL screen variables
    uic_scrTestMachine = NULL;
    ui_scrTestMachine = NULL;
    ui_ProcessFlow1 = NULL;
    ui_ProcessFlowImage1 = NULL;
    uic_testSumpPump = NULL;
    ui_testSumpPump = NULL;
    uic_testScrewPress = NULL;
    ui_testScrewPress = NULL;
    uic_testTopGate = NULL;
    ui_testTopGate = NULL;
    uic_testBottomGate = NULL;
    ui_testBottomGate = NULL;
    uic_testHeater = NULL;
    ui_testHeater = NULL;
    uic_testMixer = NULL;
    ui_testMixer = NULL;
    uic_testSettlingTankPump = NULL;
    ui_testSettlingTankPump = NULL;
    uic_testFilterTankPump = NULL;
    ui_testFilterTankPump = NULL;
    uic_TestUpperLimitSettlingTank = NULL;
    ui_TestUpperLimitSettlingTank = NULL;
    uic_TestLowerLimitSettlingTank = NULL;
    ui_TestLowerLimitSettlingTank = NULL;
    uic_TestLowerLimitFilterTank = NULL;
    ui_TestLowerLimitFilterTank = NULL;
    uic_TestUpperLimitFilterTank = NULL;
    ui_TestUpperLimitFilterTank = NULL;
    uic_TestUpperLimitInputTank = NULL;
    ui_TestUpperLimitInputTank = NULL;
    uic_TestLowerLimitInputTank = NULL;
    ui_TestLowerLimitInputTank = NULL;
    uic_TestUpperLimitMixer = NULL;
    ui_TestUpperLimitMixer = NULL;
    uic_btnStopTest = NULL;
    ui_btnStopTest = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;

}
