#!/usr/bin/env python3
"""Convert Process Flow Water Sepparator PNG to LVGL RGB565A8 C array."""
from PIL import Image
import struct, os

SRC = r'C:\Users\janre\SquareLine\assets\Process Flow Water Sepparator.png'
DST = r'C:\ESP PROJECTS\FarmWasteSolidAndLiquidSeparatorMachine\main\ui\images\ui_img_process_flow_water_sepparator_png.c'

# Resize to fill container width (875px) while preserving aspect ratio 816:415 = 1.966:1
# Container is 875x500; image at 875x445 fills width with 27.5px top+bottom padding
# Use source PNG as-is at 816x415 (no resize)
W, H = 816, 415

# Stride: 816*3=2448 bytes per row (exactly 4-byte aligned, no padding needed)
STRIDE_RAW = W * 3       # 2448
PAD = (4 - STRIDE_RAW % 4) % 4  # 0
STRIDE = STRIDE_RAW + PAD        # 2448

img = Image.open(SRC).convert('RGBA')
# No resize — use source PNG at its native size (816x415)
pixels = list(img.getdata())

data = bytearray()
for row_y in range(H):
    for row_x in range(W):
        r, g, b, a = pixels[row_y * W + row_x]
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        data += struct.pack('<H', rgb565)
        data.append(a)
    data += b'\x00' * PAD  # stride alignment padding

assert len(data) == H * STRIDE, f"Expected {H*STRIDE} bytes, got {len(data)}"
print(f'Pixels: {W*H}, raw: {W*H*3} B, with padding: {len(data)} B, stride: {STRIDE}')

BYTES_PER_ROW = 16
rows = []
for i in range(0, len(data), BYTES_PER_ROW):
    chunk = data[i : i + BYTES_PER_ROW]
    rows.append('    ' + ','.join(f'0x{b:02X}' for b in chunk) + ',')

with open(DST, 'w', newline='\n') as f:
    f.write('// This file was generated by SquareLine Studio\n')
    f.write('// SquareLine Studio version: SquareLine Studio 1.6.1\n')
    f.write('// LVGL version: 9.2.2\n')
    f.write('// Project name: Water Sepparator\n')
    f.write('\n')
    f.write('#include "../ui.h"\n')
    f.write('\n')
    f.write('#ifndef LV_ATTRIBUTE_MEM_ALIGN\n')
    f.write('    #define LV_ATTRIBUTE_MEM_ALIGN\n')
    f.write('#endif\n')
    f.write('\n')
    f.write(f'// IMAGE DATA: assets/Process Flow Water Sepparator.png  (native size {W}x{H})\n')
    f.write(f'// stride={STRIDE} ({STRIDE_RAW} data + {PAD} padding bytes per row for 4-byte alignment)\n')
    f.write('const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_process_flow_water_sepparator_png_data[]  = {\n')
    f.write('\n'.join(rows))
    f.write('\n};\n')
    f.write('const lv_image_dsc_t ui_img_process_flow_water_sepparator_png = {\n')
    f.write(f'    .header.w = {W},\n')
    f.write(f'    .header.h = {H},\n')
    f.write(f'    .header.stride = {STRIDE},\n')
    f.write('    .data_size = sizeof(ui_img_process_flow_water_sepparator_png_data),\n')
    f.write('    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,\n')
    f.write('    .header.magic = LV_IMAGE_HEADER_MAGIC,\n')
    f.write('    .data = ui_img_process_flow_water_sepparator_png_data\n')
    f.write('};\n')

print(f'Written {os.path.getsize(DST)/1024/1024:.2f} MB -> {DST}')
