#!/usr/bin/env python3
"""Resize PNG and convert to LVGL RGB565A8 C array for ESP32-P4 display."""
from PIL import Image
import struct, os

SRC = r'C:\Users\janre\SquareLine\assets\Asset 4@4x.png'
DST = r'C:\ESP PROJECTS\FarmWasteSolidAndLiquidSeparatorMachine\main\ui\images\ui_img_1839083635.c'
# Preserve original aspect ratio (2786x1417 = 1.966:1) at the original rendered size
# Original: scale=75/256 → 2786*75/256=816px, 1417*75/256=415px
W, H = 816, 415
# Stride: 816*3=2448 bytes per row (already 4-byte aligned, no padding needed)
STRIDE = W * 3  # 2448

img = Image.open(SRC).convert('RGBA').resize((W, H), Image.LANCZOS)
pixels = list(img.getdata())

# Build RGB565A8 byte stream (LVGL LV_COLOR_FORMAT_NATIVE_WITH_ALPHA, depth=16)
data = bytearray()
for r, g, b, a in pixels:
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    data += struct.pack('<H', rgb565)  # little-endian 16-bit colour
    data.append(a)                    # 8-bit alpha

print(f'Pixels: {len(pixels)}, bytes: {len(data)}, expected: {W*H*3}')

# Generate C hex rows
BYTES_PER_ROW = 16
rows = []
for i in range(0, len(data), BYTES_PER_ROW):
    chunk = data[i : i + BYTES_PER_ROW]
    rows.append('    ' + ','.join(f'0x{b:02X}' for b in chunk) + ',')
hex_block = '\n'.join(rows)

c_source = (
    "// This file was generated by SquareLine Studio\n"
    "// SquareLine Studio version: SquareLine Studio 1.6.1\n"
    "// LVGL version: 9.2.2\n"
    "// Project name: Water Sepparator\n"
    "\n"
    '#include "../ui.h"\n'
    "\n"
    "#ifndef LV_ATTRIBUTE_MEM_ALIGN\n"
    "    #define LV_ATTRIBUTE_MEM_ALIGN\n"
    "#endif\n"
    "\n"
    f"// IMAGE DATA: assets/Asset 4@4x.png  (resized {W}x{H}, preserving original 1.966:1 aspect ratio)\n"
    "const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_1839083635_data[]  = {\n"
    + hex_block + "\n"
    "};\n"
    "const lv_image_dsc_t ui_img_1839083635 = {\n"
    f"    .header.w = {W},\n"
    f"    .header.h = {H},\n"
    f"    .header.stride = {STRIDE},\n"
    "    .data_size = sizeof(ui_img_1839083635_data),\n"
    "    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,\n"
    "    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
    "    .data = ui_img_1839083635_data\n"
    "};\n"
)

with open(DST, 'w', newline='\n') as f:
    f.write(c_source)

print(f'Written {os.path.getsize(DST)/1024/1024:.2f} MB  ->  {DST}')
