// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Water Sepparator

#ifndef _WATER_SEPPARATOR_UI_H
#define _WATER_SEPPARATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_scrSplashScreen.h"
#include "screens/ui_scrRunAuto.h"
#include "screens/ui_scrMainMenu.h"
#include "screens/ui_scrSettings.h"
#include "screens/ui_scrTestMachine.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1396634952);    // assets/BatStateU-NEU-Logo 1.png
LV_IMG_DECLARE(ui_img_1839083635);    // assets/Asset 4@4x.png
LV_IMG_DECLARE(ui_img_process_flow_water_sepparator_png);    // assets/Process Flow Water Sepparator.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
